# Generated by Django 5.2.1 on 2025-05-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificateentry_resumeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateentry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/certificates/'),
        ),
    ]
