# Generated by Django 5.2.1 on 2025-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_certificateentry_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateentry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
