# Generated by Django 5.2.1 on 2025-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_certificateentry_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='about/')),
                ('skills', models.TextField(help_text='Comma-separated skills')),
            ],
        ),
    ]
